name: React App Deployment.

on:
    push:
        branches: ["main"]
        paths:
            - ".github/workflows/reactDeployment.yml"
            - "App/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 19.7.x
                  cache: "npm"
                  cache-dependency-path: ./App/package-lock.json

            - name: Install node modules.
              run: |
                  cd ./App/;
                  npm ci;
                  npm run build --if-present;

            - name: Deploy React App.
              run: |
                  cd ./App/;
                  
                  git config remote.origin.url 'https://${{ secrets.DEPLOYMENT_TOKEN }}@github.com/${{ github.repository }}.git'
                  
                  git config --global user.name $user_name
                  git config --global user.email $user_email

                  npm run deploy
              env:
                  user_name: "Tauane Sales"
                  user_email: "taysales6@gmail.com"
